name: 'v1'
on:
  push:
    branches:
      - master
    paths:
      - 'v1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./v${{ env.VERSION }}/
          push: true
          tags: |
            tuzex/composer:${{ env.VERSION }}
            ghcr.io/tuzex/composer:${{ env.VERSION }}
